<?php
// HR Traders Installer Setup Page
// Helps configure MySQL database without requiring terminal access

$message = "";
$status = "";

$script_dir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));
$base_url = preg_replace('/(\/(admin|pos|api|includes|config|database)(\/.*)?)$/i', '', $script_dir);
$base_url = '/' . trim($base_url, '/') . '/';
if ($base_url === '//') {
    $base_url = '/';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = $_POST['db_name'] ?? 'hr_traders';

    try {
        // 1. Connect without db name first
        $conn = new PDO("mysql:host=$db_host;charset=utf8mb4", $db_user, $db_pass);
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // 2. Create database
        $conn->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $conn->exec("USE `$db_name`");
        
        // 3. Read SQL schema
        $sql_file = __DIR__ . '/database/schema.sql';
        if (!file_exists($sql_file)) {
            throw new Exception("Schema file not found at: database/schema.sql");
        }
        
        $sql = file_get_contents($sql_file);
        
        // Remove comments
        $sql = preg_replace('/--.*\n/', '', $sql);
        
        // Split by semicolon, ignoring inside quotes (simple parser)
        $queries = explode(';', $sql);
        
        $conn->beginTransaction();
        foreach ($queries as $query) {
            $query = trim($query);
            if (!empty($query)) {
                $conn->exec($query);
            }
        }
        $conn->commit();
        
        // 4. Write database configuration file db.php
        $config_template = <<<'EOD'
<?php
// HR Traders Central Configuration File
// Automatically generated by installer

ob_start();

if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Determine web-accessible base path dynamically (supports subdirectories like /HR Traders/ or root domain)
$script_dir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));
$base_url = preg_replace('/(\/(admin|pos|api|includes|config|database)(\/.*)?)$/i', '', $script_dir);
$base_url = '/' . trim($base_url, '/') . '/';
if ($base_url === '//') {
    $base_url = '/';
}
define('BASE_URL', $base_url);

// Automatic offline Tailwind CDN downloader hook
$tailwind_local = __DIR__ . '/../assets/js/tailwind.min.js';
if (!file_exists($tailwind_local)) {
    $dir = dirname($tailwind_local);
    if (!is_dir($dir)) {
        @mkdir($dir, 0777, true);
    }
    $url = 'https://cdn.tailwindcss.com';
    $data = @file_get_contents($url);
    if (!$data && function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $data = curl_exec($ch);
        curl_close($ch);
    }
    if ($data) {
        @file_put_contents($tailwind_local, $data);
    }
}

define('DB_HOST', '{{DB_HOST}}');
define('DB_USER', '{{DB_USER}}');
define('DB_PASS', '{{DB_PASS}}');
define('DB_NAME', '{{DB_NAME}}');

define('STORE_NAME', 'HR Traders');
define('CURRENCY', 'Rs.');
define('WHATSAPP_NUMBER', '923001234567'); // WhatsApp shop number

try {
    $pdo = new PDO(
        "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4",
        DB_USER,
        DB_PASS,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]
    );
} catch (PDOException $e) {
    die("Database Connection Failed: " . $e->getMessage() . "<br><br><strong>Tip:</strong> If you are setting up the system for the first time, run the <a href='" . BASE_URL . "install.php' style='color:blue;text-decoration:underline;'>System Installer (install.php)</a> to automatically create the database and tables.");
}

$CATEGORIES = [
    'anaj' => [
        'name' => 'Anaj',
        'urdu' => 'اناج'
    ],
    'ice_cream' => [
        'name' => 'Ice Cream',
        'urdu' => 'آئس کریم',
        'alert' => 'Available for nearby locations only'
    ],
    'beverages' => [
        'name' => 'Beverages',
        'urdu' => 'مشروبات'
    ],
    'milk' => [
        'name' => 'Milk',
        'urdu' => 'دودھ'
    ],
    'cosmetics' => [
        'name' => 'Cosmetics',
        'urdu' => 'کاسمیٹکس'
    ],
    'snacks' => [
        'name' => 'Snacks',
        'urdu' => 'سنیکس'
    ],
    'bakery' => [
        'name' => 'Bakery',
        'urdu' => 'بیکری'
    ],
    'sauce' => [
        'name' => 'Sauce',
        'urdu' => 'سوس'
    ],
    // Sub-items map to Cosmetics for unified display
    'shampoo' => [
        'name' => 'Cosmetics (Shampoo)',
        'urdu' => 'کاسمیٹکس (شیمپو)',
        'parent' => 'cosmetics'
    ],
    'soap' => [
        'name' => 'Cosmetics (Soap)',
        'urdu' => 'کاسمیٹکس (صابن)',
        'parent' => 'cosmetics'
    ],
    'toothpaste' => [
        'name' => 'Cosmetics (Toothpaste)',
        'urdu' => 'کاسمیٹکس (ٹوتھ پیسٹ)',
        'parent' => 'cosmetics'
    ],
    'body_wash' => [
        'name' => 'Cosmetics (Body Wash)',
        'urdu' => 'کاسمیٹکس (باڈی واش)',
        'parent' => 'cosmetics'
    ],
    'deodorant' => [
        'name' => 'Cosmetics (Deodorant)',
        'urdu' => 'کاسمیٹکس (ڈیوڈرینٹ)',
        'parent' => 'cosmetics'
    ]
];
EOD;

        $config_content = str_replace(
            ['{{DB_HOST}}', '{{DB_USER}}', '{{DB_PASS}}', '{{DB_NAME}}'],
            [$db_host, $db_user, $db_pass, $db_name],
            $config_template
        );
        file_put_contents(__DIR__ . '/config/db.php', $config_content);

        $status = "success";
        $message = "Database configured and schema installed successfully! Default users created: <strong>owner / admin123</strong> and <strong>manager / admin123</strong>. Please delete <code>install.php</code> before going live.";

    } catch (Exception $e) {
        $status = "error";
        $message = "Installation Failed: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HR Traders - Web Installer</title>
    <!-- Fallback custom styling for offline readiness -->
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #f1f5f9;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0;
            padding: 20px;
        }
        .container {
            background: rgba(30, 41, 59, 0.7);
            backdrop-filter: blur(12px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 30px;
            max-width: 500px;
            width: 100%;
            box-shadow: 0 10px 25px rgba(0,0,0,0.5);
        }
        h2 { margin-top: 0; text-align: center; color: #10b981; }
        .form-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-weight: 500; font-size: 14px; }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            background: #0f172a;
            border: 1px solid #334155;
            border-radius: 8px;
            color: #fff;
            box-sizing: border-box;
        }
        button {
            width: 100%;
            padding: 12px;
            background: #10b981;
            color: #fff;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.3s;
        }
        button:hover { background: #059669; }
        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            font-size: 14px;
            line-height: 1.5;
        }
        .alert-success { background: rgba(16, 185, 129, 0.2); border: 1px solid #10b981; color: #34d399; }
        .alert-error { background: rgba(239, 68, 68, 0.2); border: 1px solid #ef4444; color: #f87171; }
        .info-text { font-size: 12px; color: #94a3b8; text-align: center; margin-top: 15px; }
    </style>
</head>
<body>

<div class="container">
    <h2>HR Traders Installer</h2>
    <p style="text-align:center; color:#94a3b8; margin-bottom:25px;">Enter your local MySQL credentials to initialize the database.</p>
    
    <?php if (!empty($message)): ?>
        <div class="alert alert-<?php echo $status; ?>">
            <?php echo $message; ?>
        </div>
        <?php if ($status === 'success'): ?>
            <a href="<?php echo $base_url; ?>" style="display:block; text-align:center; margin-top:15px; color:#10b981; font-weight:600; text-decoration:none;">Go to Homepage &rarr;</a>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($status !== 'success'): ?>
    <form action="install.php" method="POST">
        <div class="form-group">
            <label for="db_host">Host Name / Server</label>
            <input type="text" id="db_host" name="db_host" value="localhost" required>
        </div>
        <div class="form-group">
            <label for="db_user">Username</label>
            <input type="text" id="db_user" name="db_user" value="root" required>
        </div>
        <div class="form-group">
            <label for="db_pass">Password</label>
            <input type="password" id="db_pass" name="db_pass" placeholder="Usually empty on Local XAMPP/WAMP">
        </div>
        <div class="form-group">
            <label for="db_name">Database Name</label>
            <input type="text" id="db_name" name="db_name" value="hr_traders" required>
        </div>
        <button type="submit">Initialize System</button>
    </form>
    <?php endif; ?>

    <p class="info-text">Note: This will set up tables and default records automatically.</p>
</div>

</body>
</html>
