-- HR TRADERS POSTGRESQL SCHEMA (SUPABASE COMPATIBLE)
-- Copy and run this script in the Supabase SQL Editor.

-- Enable UUID generation extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES TABLE (Linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE,
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('owner', 'manager', 'customer')),
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10,2) NOT NULL,
    purchase_price NUMERIC(10,2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    weight TEXT,
    unit TEXT DEFAULT 'pcs',
    category TEXT NOT NULL,
    image TEXT,
    old_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    discount_percentage INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Products Policies
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Products are manageable by admins" ON public.products FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID REFERENCES auth.users ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    payment_method TEXT NOT NULL DEFAULT 'COD',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'packaging', 'out_for_delivery', 'delivered', 'cancelled')),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Orders Policies
CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Anyone can create orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Orders are manageable by admins" ON public.orders FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 4. ORDER ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on order_items
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Order Items Policies
CREATE POLICY "Anyone can insert order items" ON public.order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can view their own order items" ON public.order_items FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.orders 
        WHERE orders.id = order_id AND (orders.customer_id = auth.uid() OR auth.uid() IS NULL)
    )
);
CREATE POLICY "Order items are manageable by admins" ON public.order_items FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 5. SALES TABLE (POS & Consolidated Sales Reports)
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type TEXT NOT NULL DEFAULT 'POS' CHECK (transaction_type IN ('POS', 'Online')),
    order_id BIGINT REFERENCES public.orders ON DELETE SET NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    total_profit NUMERIC(10,2) NOT NULL,
    payment_method TEXT NOT NULL DEFAULT 'Cash',
    cashier_id UUID REFERENCES auth.users ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on sales
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- Sales Policies
CREATE POLICY "Sales are viewable/manageable by admins" ON public.sales FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 6. SALE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.sales ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products ON DELETE SET NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    purchase_price NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on sale_items
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;

-- Sale Items Policies
CREATE POLICY "Sale items are viewable/manageable by admins" ON public.sale_items FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 7. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key_name TEXT PRIMARY KEY,
    val_value TEXT
);

-- Enable RLS on settings
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- Settings Policies
CREATE POLICY "Settings are viewable by everyone" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Settings are manageable by admins" ON public.settings FOR ALL TO authenticated USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
) WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 8. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products ON DELETE CASCADE NOT NULL,
    customer_name TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Reviews Policies
CREATE POLICY "Reviews are viewable by everyone" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Reviews can be created by anyone" ON public.reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Reviews are deleteable by admins" ON public.reviews FOR DELETE USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- SEED DATA FOR SYSTEM SETTINGS
INSERT INTO public.settings (key_name, val_value) VALUES
('active_theme', 'emerald_green'),
('shop_status', 'open'),
('low_stock_threshold', '5'),
('homepage_announcement', 'Welcome to HR Traders! Shop the freshest organic grains, cosmetics, and cold beverages online. Order now for home delivery!'),
('whatsapp_dispatch_template', 'Hi {name}, your order #{ref} has been dispatched! Total Invoice: {total}. Delivery Address: {address}. Thank you for shopping with HR Traders!'),
('shop_timings', '{"Saturday":"6:00 AM - 12:00 PM","Sunday":"6:00 AM - 12:00 PM","Monday":"6:00 AM - 12:00 PM","Tuesday":"6:00 AM - 12:00 PM","Wednesday":"6:00 AM - 12:00 PM","Thursday":"6:00 AM - 12:00 PM","Friday":"6:00 AM - 12:00 PM & 4:00 PM - 12:00 AM"}')
ON CONFLICT (key_name) DO NOTHING;

-- SEED DUMMY PRODUCTS FOR RETAIL SETUP
INSERT INTO public.products (barcode, name, description, price, purchase_price, stock_quantity, weight, unit, category) VALUES
('11111111', 'Premium Basmati Rice', 'High quality extra long grain aromatic rice.', 320.00, 260.00, 150, '1 kg', 'kg', 'anaj'),
('22222222', 'Daal Chana (Gram Lentils)', 'Clean and washed split gram pulses.', 280.00, 220.00, 200, '1 kg', 'kg', 'anaj'),
('33333333', 'Daal Mash (Urad Lentils)', 'Spiceless premium white lentils.', 450.00, 380.00, 80, '1 kg', 'kg', 'anaj'),
('44444444', 'Sunsilk Shampoo', 'Softening and shining hair shampoo bottle.', 350.00, 290.00, 120, '180 ml', 'pcs', 'shampoo'),
('55555555', 'Lifebuoy Soap Red', 'Germ protection hand washing soap bar.', 90.00, 75.00, 250, '115 g', 'pcs', 'soap'),
('66666666', 'Coca Cola Regular Can', 'Carbonated cold soft drink.', 150.00, 120.00, 500, '250 ml', 'pcs', 'cold_drinks'),
('77777777', 'Nestle Pure Life Water', 'Pure drinking mineral water bottle.', 90.00, 70.00, 600, '1.5 Litre', 'pcs', 'water'),
('88888888', 'Gourmet Chocolate Ice Cream', 'Creamy rich chocolate family pack ice cream.', 650.00, 520.00, 45, '1 Litre', 'pcs', 'ice_cream'),
('99999999', 'Nestle Milkpak', 'UHT processed premium milk pack.', 290.00, 240.00, 180, '1 Litre', 'pcs', 'milk')
ON CONFLICT (barcode) DO NOTHING;

-- 9. PRODUCT DEMANDS TABLE
CREATE TABLE IF NOT EXISTS public.product_demands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    demand_details TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on product_demands
ALTER TABLE public.product_demands ENABLE ROW LEVEL SECURITY;

-- Product Demands Policies
CREATE POLICY "Anyone can insert product demands" ON public.product_demands FOR INSERT WITH CHECK (true);
CREATE POLICY "Product demands are viewable/manageable by admins" ON public.product_demands FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 10. VISITOR LOGS TABLE
CREATE TABLE IF NOT EXISTS public.visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_agent TEXT,
    language TEXT,
    ip TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on visitor_logs
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;

-- Visitor Logs Policies
CREATE POLICY "Anyone can insert visitor logs" ON public.visitor_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Visitor logs are viewable by admins" ON public.visitor_logs FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 11. PUSH SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_phone TEXT,
    subscription JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on push_subscriptions
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Push Subscriptions Policies
CREATE POLICY "Anyone can insert push subscriptions" ON public.push_subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Push subscriptions are viewable/manageable by admins" ON public.push_subscriptions FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('owner', 'manager')
    )
);

-- 12. PROMO AD CONFIG SEEDS
INSERT INTO public.settings (key_name, val_value) VALUES
('promo_ad_enabled', 'false'),
('promo_ad_image', ''),
('promo_ad_link', '')
ON CONFLICT (key_name) DO NOTHING;
